interface Props { size?: number }

// Logo is a baked composite (Octra ring + AC ski mask peeking out of the
// middle), generated by claim-site/scripts/gen-icons.mjs. We just <img> it.
export function Logo({ size = 22 }: Props) {
  return (
    <img
      src={chrome.runtime.getURL('icons/icon128.png')}
      width={size}
      height={size}
      alt=""
      style={{ display: 'inline-block', flexShrink: 0 }}
    />
  );
}
